# Generated by Django 3.0.7 on 2020-08-25 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('catagory', models.CharField(max_length=100)),
                ('card_content', models.TextField(max_length=7000)),
                ('content', models.TextField(max_length=7000)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_image', models.ImageField(blank=True, default='default.jpg', upload_to='blog_images')),
            ],
        ),
    ]
