# Generated by Django 3.0.7 on 2020-09-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200827_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='chek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='popular',
            new_name='latest_story',
        ),
        migrations.AddField(
            model_name='post',
            name='mba_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='startup_story',
            field=models.BooleanField(default=False),
        ),
    ]
