# Generated by Django 3.0.7 on 2020-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post_trending_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='trending_story',
            field=models.BooleanField(default=False),
        ),
    ]
