# Generated by Django 3.0.7 on 2020-09-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_carousel'),
        ('home', '0008_auto_20200926_1630'),
    ]

    operations = [
    ]
