# Generated by Django 3.0.7 on 2020-09-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20200926_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
