# Generated by Django 3.0.7 on 2020-10-07 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organiser_name', models.CharField(default='Enter Organiser Name', max_length=50)),
                ('organiser_email', models.CharField(default='Enter Organiser Email', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(default='About the event', max_length=20000)),
                ('registration_open', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_close', models.DateTimeField(default=django.utils.timezone.now)),
                ('min_size', models.IntegerField(default=1)),
                ('max_size', models.IntegerField(default=1)),
                ('image', models.ImageField(default='competition/default.png', upload_to='competition/')),
                ('team_link', models.CharField(default='', max_length=100)),
                ('registered', models.IntegerField(default=0)),
                ('competition_popular', models.BooleanField(default=False)),
                ('file', models.FileField(default='competition/default.png', upload_to='file/')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('contact_no', phone_field.models.PhoneField(help_text='Add country code before the contact no.', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_event', to='competition.competition')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_submit/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_competition', to='competition.competition')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College', models.CharField(default='Enter Your College Name', max_length=50)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='competition.competition')),
                ('team_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='prizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('reward', models.CharField(max_length=20)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='competition.competition')),
            ],
        ),
    ]
