# Generated by Django 3.0.7 on 2020-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='about',
            field=models.TextField(default='About the event', max_length=20000, null=True),
        ),
    ]
