# Generated by Django 3.0.7 on 2020-09-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='registered',
            field=models.IntegerField(default=0),
        ),
    ]
