# Generated by Django 3.0.7 on 2020-09-20 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
