# Generated by Django 3.0.7 on 2020-09-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_competition_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='popular',
            new_name='competition_popular',
        ),
    ]
