# Generated by Django 3.0.7 on 2020-09-23 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
