# Generated by Django 3.0.7 on 2020-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_competition_event_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='clg',
        ),
        migrations.AddField(
            model_name='register',
            name='College',
            field=models.CharField(default='Enter Your College Name', max_length=50),
        ),
    ]
