# Generated by Django 3.0.7 on 2020-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_auto_20200923_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='file',
            field=models.FileField(default='competition/default.png', upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='file',
            field=models.FileField(upload_to='file_submit/'),
        ),
    ]
