# Generated by Django 3.0.7 on 2020-09-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_auto_20200924_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='begin_date',
            new_name='registration_deadline',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='event_date',
            new_name='registration_open',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='event_end',
            new_name='submission_close',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='last_date',
            new_name='submission_start',
        ),
    ]
