# Generated by Django 3.0.7 on 2020-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_competition_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='team_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
